name: CI

on: [push, pull_request]

jobs:
  gitHubActionForPytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    name: GitHub Action
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt -r requirements-dev.txt
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make coverage
