name: CI

on: [push, pull_request]

jobs:
  gitHubActionForPytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    name: GitHub Action
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install pylint==2.15.5
    - name: Lint
      run: |
        make lint
